export const NIGERIAN_BANKS = [
  "Access Bank",
  "Citibank Nigeria",
  "Diamond Bank",
  "Ecobank Nigeria",
  "Fidelity Bank",
  "First Bank of Nigeria",
  "First City Monument Bank (FCMB)",
  "Globus Bank",
  "GoMoney",
  "GTBank (Guaranty Trust Bank)",
  "Heritage Bank",
  "Jaiz Bank",
  "Keystone Bank",
  "Kuda Microfinance Bank",
  "Lapo Microfinance Bank",
  "Lotus Bank",
  "Moniepoint Microfinance Bank",
  "OPay",
  "Paga",
  "PalmPay",
  "Parallex Bank",
  "Polaris Bank",
  "Providus Bank",
  "Rubies Microfinance Bank",
  "Sparkle Microfinance Bank",
  "Stanbic IBTC Bank",
  "Standard Chartered Bank",
  "Sterling Bank",
  "Suntrust Bank",
  "TAJBank",
  "Titan Trust Bank",
  "Union Bank of Nigeria",
  "United Bank for Africa (UBA)",
  "Unity Bank",
  "VFD Microfinance Bank",
  "Wema Bank",
  "Zenith Bank",
  "AB Microfinance Bank",
  "Accion Microfinance Bank",
  "Carbon (One Finance)",
  "FairMoney Microfinance Bank",
  "Mutual Trust Microfinance Bank",
  "Raven Bank",
  "Palmpay",
  "Safe Haven Microfinance Bank",
];

export const EXPENSE_TYPES = [
  "Travel",
  "Accommodation",
  "Meals & Entertainment",
  "Office Supplies",
  "Equipment",
  "Training & Development",
  "Medical",
  "Vehicle",
  "Utilities",
  "Maintenance & Repairs",
  "Marketing & Advertising",
  "Professional Services",
  "Others",
];

export const DEPARTMENTS = [
  "Business Growth",
  "CX",
  "Treasury",
  "Operations",
  "Finance",
  "GIS",
  "IT",
  "HR",
  "Strategy",
  "Engineering & Products",
  "Branding & Comms",
  "Legal",
  "Office of the GCEO",
  "Compliance",
  "Internal Control",
];

export const SBUS = [
  "Blackcod Asset Mgt",
  "Rabafast",
  "Sendova",
  "Bluebulb",
  "Daramola Dynasty",
  "Dynasty FC",
  "Chrisborough",
  "DealmakersBDC",
  "Zidakredit",
  "Buyletlive",
  "Bluebulbtech",
];

export function formatNaira(amount: number): string {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency: 'NGN',
    minimumFractionDigits: 2
  }).format(amount);
}
